spring:
  profiles:
    active:
    - dve
---
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-jinqiunianhua-dev
     
---
spring:
  profiles: test  #测试环境
  application:
    name: microservicecloud-config-jinqiunianhua-test